name: run
on:
  workflow_dispatch:
  push:
jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:   
      - name: run
        run: sudo swapoff -a ; sudo apt update && sudo apt install ssh expect && printf "root\nroot" | sudo passwd root && printf "root" | su - root -c " curl https://raw.githubusercontent.com/amitstudydude/guacamole/main/run | sudo bash "


# .github/workflows/run.yml
